name: CD
on: 
  push:
    branches: [ main ]

jobs:
  apply:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Terraform apply for prod.tfvars
        run: >
          TF_VAR_k8s_host=${{ secrets.K8S_HOST }}
          TF_VAR_k8s_client_certificate=${{ secrets.K8S_CLIENT_CERTIFICATE }}
          TF_VAR_k8s_client_key=${{ secrets.K8S_CLIENT_KEY }}
          TF_VAR_k8s_cluster_ca_certificate=${{ secrets.K8S_CLUSTER_CA_CERTIFICATE}}
          terraform -chdir=./src/ apply -var-file=../deployments/prod.tfvars -auto-approve
